title: International Press journal GIC author support
description: TeX related material for the manuscript preparation for the 
             International Press journal Geometry, Imaging and Computing
             (GIC)
show_downloads: true
theme: jekyll-theme-tactile
